/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AdminStats {
  'totalOrders' : bigint,
  'totalCommission' : bigint,
  'totalRevenue' : bigint,
  'pendingVerifications' : bigint,
}
export interface Analytics {
  'growth' : number,
  'topCategories' : Array<[string, bigint]>,
  'monthlyRevenue' : Array<bigint>,
}
export interface CartItem {
  'productId' : ProductId,
  'quantity' : bigint,
  'price' : bigint,
}
export interface Order {
  'id' : OrderId,
  'status' : string,
  'deliveryAddress' : string,
  'createdAt' : Timestamp,
  'totalAmount' : bigint,
  'paymentId' : string,
  'commissionAmount' : bigint,
  'customerId' : UserId,
  'items' : Array<OrderItem>,
}
export type OrderId = string;
export interface OrderItem {
  'productId' : ProductId,
  'productName' : string,
  'sellerName' : string,
  'quantity' : bigint,
  'price' : bigint,
}
export interface Product {
  'id' : ProductId,
  'city' : string,
  'name' : string,
  'createdAt' : Timestamp,
  'description' : string,
  'sellerName' : string,
  'stock' : bigint,
  'isVerified' : boolean,
  'category' : string,
  'sellerId' : SellerId,
  'rating' : number,
  'price' : bigint,
  'reviewCount' : bigint,
  'discountedPrice' : bigint,
  'hasFastDelivery' : boolean,
  'images' : Array<string>,
}
export type ProductId = string;
export interface Review {
  'id' : ReviewId,
  'createdAt' : Timestamp,
  'productId' : ProductId,
  'comment' : string,
  'customerId' : UserId,
  'rating' : bigint,
}
export type ReviewId = string;
export interface Seller {
  'id' : SellerId,
  'shopImage' : string,
  'city' : string,
  'name' : string,
  'joinedAt' : Timestamp,
  'description' : string,
  'totalSales' : bigint,
  'isVerified' : boolean,
  'shopName' : string,
  'commissionRate' : number,
  'pincode' : string,
}
export type SellerId = string;
export interface ShoppingItem {
  'productName' : string,
  'currency' : string,
  'quantity' : bigint,
  'priceInCents' : bigint,
  'productDescription' : string,
}
export interface StripeConfiguration {
  'allowedCountries' : Array<string>,
  'secretKey' : string,
}
export type StripeSessionStatus = {
    'completed' : { 'userPrincipal' : [] | [string], 'response' : string }
  } |
  { 'failed' : { 'error' : string } };
export type Timestamp = bigint;
export interface TransformationInput {
  'context' : Uint8Array,
  'response' : http_request_result,
}
export interface TransformationOutput {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export type UserId = Principal;
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _ImmutableObjectStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _ImmutableObjectStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _ImmutableObjectStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface http_header { 'value' : string, 'name' : string }
export interface http_request_result {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface _SERVICE {
  '_immutableObjectStorageBlobsAreLive' : ActorMethod<
    [Array<Uint8Array>],
    Array<boolean>
  >,
  '_immutableObjectStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_immutableObjectStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_immutableObjectStorageCreateCertificate' : ActorMethod<
    [string],
    _ImmutableObjectStorageCreateCertificateResult
  >,
  '_immutableObjectStorageRefillCashier' : ActorMethod<
    [[] | [_ImmutableObjectStorageRefillInformation]],
    _ImmutableObjectStorageRefillResult
  >,
  '_immutableObjectStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControl' : ActorMethod<[], undefined>,
  'addReview' : ActorMethod<[ProductId, bigint, string], Review>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createCheckoutSession' : ActorMethod<
    [Array<ShoppingItem>, string, string],
    string
  >,
  'createOrder' : ActorMethod<[Array<CartItem>, bigint, string], Order>,
  'deleteProduct' : ActorMethod<[ProductId], undefined>,
  'getAdminStats' : ActorMethod<[], AdminStats>,
  'getAllOrders' : ActorMethod<[], Array<Order>>,
  'getAllUsers' : ActorMethod<[], Array<Principal>>,
  'getAnalytics' : ActorMethod<[], Analytics>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getFeaturedProducts' : ActorMethod<[], Array<Product>>,
  'getOrderById' : ActorMethod<[OrderId], [] | [Order]>,
  'getOrders' : ActorMethod<[string], Array<Order>>,
  'getProductById' : ActorMethod<[ProductId], [] | [Product]>,
  'getProducts' : ActorMethod<[], Array<Product>>,
  'getProductsByCategory' : ActorMethod<[string], Array<Product>>,
  'getReviews' : ActorMethod<[ProductId], Array<Review>>,
  'getSellerEarnings' : ActorMethod<[SellerId], bigint>,
  'getSellerOrders' : ActorMethod<[SellerId], Array<Order>>,
  'getSellerProducts' : ActorMethod<[SellerId], Array<Product>>,
  'getSellers' : ActorMethod<[], Array<Seller>>,
  'getStripeSessionStatus' : ActorMethod<[string], StripeSessionStatus>,
  'getVerifiedSellers' : ActorMethod<[], Array<Seller>>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'isStripeConfigured' : ActorMethod<[], boolean>,
  'setStripeConfiguration' : ActorMethod<[StripeConfiguration], undefined>,
  'transform' : ActorMethod<[TransformationInput], TransformationOutput>,
  'updateOrderStatus' : ActorMethod<[OrderId, string], boolean>,
  'upsertProduct' : ActorMethod<[Product], undefined>,
  'verifySeller' : ActorMethod<[SellerId], boolean>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];