/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _ImmutableObjectStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _ImmutableObjectStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _ImmutableObjectStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const ProductId = IDL.Text;
export const ReviewId = IDL.Text;
export const Timestamp = IDL.Int;
export const UserId = IDL.Principal;
export const Review = IDL.Record({
  'id' : ReviewId,
  'createdAt' : Timestamp,
  'productId' : ProductId,
  'comment' : IDL.Text,
  'customerId' : UserId,
  'rating' : IDL.Nat,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const ShoppingItem = IDL.Record({
  'productName' : IDL.Text,
  'currency' : IDL.Text,
  'quantity' : IDL.Nat,
  'priceInCents' : IDL.Nat,
  'productDescription' : IDL.Text,
});
export const CartItem = IDL.Record({
  'productId' : ProductId,
  'quantity' : IDL.Nat,
  'price' : IDL.Nat,
});
export const OrderId = IDL.Text;
export const OrderItem = IDL.Record({
  'productId' : ProductId,
  'productName' : IDL.Text,
  'sellerName' : IDL.Text,
  'quantity' : IDL.Nat,
  'price' : IDL.Nat,
});
export const Order = IDL.Record({
  'id' : OrderId,
  'status' : IDL.Text,
  'deliveryAddress' : IDL.Text,
  'createdAt' : Timestamp,
  'totalAmount' : IDL.Nat,
  'paymentId' : IDL.Text,
  'commissionAmount' : IDL.Nat,
  'customerId' : UserId,
  'items' : IDL.Vec(OrderItem),
});
export const AdminStats = IDL.Record({
  'totalOrders' : IDL.Nat,
  'totalCommission' : IDL.Nat,
  'totalRevenue' : IDL.Nat,
  'pendingVerifications' : IDL.Nat,
});
export const Analytics = IDL.Record({
  'growth' : IDL.Float64,
  'topCategories' : IDL.Vec(IDL.Tuple(IDL.Text, IDL.Nat)),
  'monthlyRevenue' : IDL.Vec(IDL.Nat),
});
export const SellerId = IDL.Text;
export const Product = IDL.Record({
  'id' : ProductId,
  'city' : IDL.Text,
  'name' : IDL.Text,
  'createdAt' : Timestamp,
  'description' : IDL.Text,
  'sellerName' : IDL.Text,
  'stock' : IDL.Nat,
  'isVerified' : IDL.Bool,
  'category' : IDL.Text,
  'sellerId' : SellerId,
  'rating' : IDL.Float64,
  'price' : IDL.Nat,
  'reviewCount' : IDL.Nat,
  'discountedPrice' : IDL.Nat,
  'hasFastDelivery' : IDL.Bool,
  'images' : IDL.Vec(IDL.Text),
});
export const Seller = IDL.Record({
  'id' : SellerId,
  'shopImage' : IDL.Text,
  'city' : IDL.Text,
  'name' : IDL.Text,
  'joinedAt' : Timestamp,
  'description' : IDL.Text,
  'totalSales' : IDL.Nat,
  'isVerified' : IDL.Bool,
  'shopName' : IDL.Text,
  'commissionRate' : IDL.Float64,
  'pincode' : IDL.Text,
});
export const StripeSessionStatus = IDL.Variant({
  'completed' : IDL.Record({
    'userPrincipal' : IDL.Opt(IDL.Text),
    'response' : IDL.Text,
  }),
  'failed' : IDL.Record({ 'error' : IDL.Text }),
});
export const StripeConfiguration = IDL.Record({
  'allowedCountries' : IDL.Vec(IDL.Text),
  'secretKey' : IDL.Text,
});
export const http_header = IDL.Record({
  'value' : IDL.Text,
  'name' : IDL.Text,
});
export const http_request_result = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});
export const TransformationInput = IDL.Record({
  'context' : IDL.Vec(IDL.Nat8),
  'response' : http_request_result,
});
export const TransformationOutput = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});

export const idlService = IDL.Service({
  '_immutableObjectStorageBlobsAreLive' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [IDL.Vec(IDL.Bool)],
      ['query'],
    ),
  '_immutableObjectStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_immutableObjectStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_immutableObjectStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_ImmutableObjectStorageCreateCertificateResult],
      [],
    ),
  '_immutableObjectStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_ImmutableObjectStorageRefillInformation)],
      [_ImmutableObjectStorageRefillResult],
      [],
    ),
  '_immutableObjectStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControl' : IDL.Func([], [], []),
  'addReview' : IDL.Func([ProductId, IDL.Nat, IDL.Text], [Review], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createCheckoutSession' : IDL.Func(
      [IDL.Vec(ShoppingItem), IDL.Text, IDL.Text],
      [IDL.Text],
      [],
    ),
  'createOrder' : IDL.Func([IDL.Vec(CartItem), IDL.Nat, IDL.Text], [Order], []),
  'deleteProduct' : IDL.Func([ProductId], [], []),
  'getAdminStats' : IDL.Func([], [AdminStats], ['query']),
  'getAllOrders' : IDL.Func([], [IDL.Vec(Order)], ['query']),
  'getAllUsers' : IDL.Func([], [IDL.Vec(IDL.Principal)], ['query']),
  'getAnalytics' : IDL.Func([], [Analytics], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getFeaturedProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
  'getOrderById' : IDL.Func([OrderId], [IDL.Opt(Order)], ['query']),
  'getOrders' : IDL.Func([IDL.Text], [IDL.Vec(Order)], ['query']),
  'getProductById' : IDL.Func([ProductId], [IDL.Opt(Product)], ['query']),
  'getProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
  'getProductsByCategory' : IDL.Func([IDL.Text], [IDL.Vec(Product)], ['query']),
  'getReviews' : IDL.Func([ProductId], [IDL.Vec(Review)], ['query']),
  'getSellerEarnings' : IDL.Func([SellerId], [IDL.Nat], ['query']),
  'getSellerOrders' : IDL.Func([SellerId], [IDL.Vec(Order)], ['query']),
  'getSellerProducts' : IDL.Func([SellerId], [IDL.Vec(Product)], ['query']),
  'getSellers' : IDL.Func([], [IDL.Vec(Seller)], ['query']),
  'getStripeSessionStatus' : IDL.Func([IDL.Text], [StripeSessionStatus], []),
  'getVerifiedSellers' : IDL.Func([], [IDL.Vec(Seller)], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'isStripeConfigured' : IDL.Func([], [IDL.Bool], ['query']),
  'setStripeConfiguration' : IDL.Func([StripeConfiguration], [], []),
  'transform' : IDL.Func(
      [TransformationInput],
      [TransformationOutput],
      ['query'],
    ),
  'updateOrderStatus' : IDL.Func([OrderId, IDL.Text], [IDL.Bool], []),
  'upsertProduct' : IDL.Func([Product], [], []),
  'verifySeller' : IDL.Func([SellerId], [IDL.Bool], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _ImmutableObjectStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _ImmutableObjectStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _ImmutableObjectStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const ProductId = IDL.Text;
  const ReviewId = IDL.Text;
  const Timestamp = IDL.Int;
  const UserId = IDL.Principal;
  const Review = IDL.Record({
    'id' : ReviewId,
    'createdAt' : Timestamp,
    'productId' : ProductId,
    'comment' : IDL.Text,
    'customerId' : UserId,
    'rating' : IDL.Nat,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const ShoppingItem = IDL.Record({
    'productName' : IDL.Text,
    'currency' : IDL.Text,
    'quantity' : IDL.Nat,
    'priceInCents' : IDL.Nat,
    'productDescription' : IDL.Text,
  });
  const CartItem = IDL.Record({
    'productId' : ProductId,
    'quantity' : IDL.Nat,
    'price' : IDL.Nat,
  });
  const OrderId = IDL.Text;
  const OrderItem = IDL.Record({
    'productId' : ProductId,
    'productName' : IDL.Text,
    'sellerName' : IDL.Text,
    'quantity' : IDL.Nat,
    'price' : IDL.Nat,
  });
  const Order = IDL.Record({
    'id' : OrderId,
    'status' : IDL.Text,
    'deliveryAddress' : IDL.Text,
    'createdAt' : Timestamp,
    'totalAmount' : IDL.Nat,
    'paymentId' : IDL.Text,
    'commissionAmount' : IDL.Nat,
    'customerId' : UserId,
    'items' : IDL.Vec(OrderItem),
  });
  const AdminStats = IDL.Record({
    'totalOrders' : IDL.Nat,
    'totalCommission' : IDL.Nat,
    'totalRevenue' : IDL.Nat,
    'pendingVerifications' : IDL.Nat,
  });
  const Analytics = IDL.Record({
    'growth' : IDL.Float64,
    'topCategories' : IDL.Vec(IDL.Tuple(IDL.Text, IDL.Nat)),
    'monthlyRevenue' : IDL.Vec(IDL.Nat),
  });
  const SellerId = IDL.Text;
  const Product = IDL.Record({
    'id' : ProductId,
    'city' : IDL.Text,
    'name' : IDL.Text,
    'createdAt' : Timestamp,
    'description' : IDL.Text,
    'sellerName' : IDL.Text,
    'stock' : IDL.Nat,
    'isVerified' : IDL.Bool,
    'category' : IDL.Text,
    'sellerId' : SellerId,
    'rating' : IDL.Float64,
    'price' : IDL.Nat,
    'reviewCount' : IDL.Nat,
    'discountedPrice' : IDL.Nat,
    'hasFastDelivery' : IDL.Bool,
    'images' : IDL.Vec(IDL.Text),
  });
  const Seller = IDL.Record({
    'id' : SellerId,
    'shopImage' : IDL.Text,
    'city' : IDL.Text,
    'name' : IDL.Text,
    'joinedAt' : Timestamp,
    'description' : IDL.Text,
    'totalSales' : IDL.Nat,
    'isVerified' : IDL.Bool,
    'shopName' : IDL.Text,
    'commissionRate' : IDL.Float64,
    'pincode' : IDL.Text,
  });
  const StripeSessionStatus = IDL.Variant({
    'completed' : IDL.Record({
      'userPrincipal' : IDL.Opt(IDL.Text),
      'response' : IDL.Text,
    }),
    'failed' : IDL.Record({ 'error' : IDL.Text }),
  });
  const StripeConfiguration = IDL.Record({
    'allowedCountries' : IDL.Vec(IDL.Text),
    'secretKey' : IDL.Text,
  });
  const http_header = IDL.Record({ 'value' : IDL.Text, 'name' : IDL.Text });
  const http_request_result = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  const TransformationInput = IDL.Record({
    'context' : IDL.Vec(IDL.Nat8),
    'response' : http_request_result,
  });
  const TransformationOutput = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  
  return IDL.Service({
    '_immutableObjectStorageBlobsAreLive' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [IDL.Vec(IDL.Bool)],
        ['query'],
      ),
    '_immutableObjectStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_immutableObjectStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_immutableObjectStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_ImmutableObjectStorageCreateCertificateResult],
        [],
      ),
    '_immutableObjectStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_ImmutableObjectStorageRefillInformation)],
        [_ImmutableObjectStorageRefillResult],
        [],
      ),
    '_immutableObjectStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControl' : IDL.Func([], [], []),
    'addReview' : IDL.Func([ProductId, IDL.Nat, IDL.Text], [Review], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createCheckoutSession' : IDL.Func(
        [IDL.Vec(ShoppingItem), IDL.Text, IDL.Text],
        [IDL.Text],
        [],
      ),
    'createOrder' : IDL.Func(
        [IDL.Vec(CartItem), IDL.Nat, IDL.Text],
        [Order],
        [],
      ),
    'deleteProduct' : IDL.Func([ProductId], [], []),
    'getAdminStats' : IDL.Func([], [AdminStats], ['query']),
    'getAllOrders' : IDL.Func([], [IDL.Vec(Order)], ['query']),
    'getAllUsers' : IDL.Func([], [IDL.Vec(IDL.Principal)], ['query']),
    'getAnalytics' : IDL.Func([], [Analytics], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getFeaturedProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
    'getOrderById' : IDL.Func([OrderId], [IDL.Opt(Order)], ['query']),
    'getOrders' : IDL.Func([IDL.Text], [IDL.Vec(Order)], ['query']),
    'getProductById' : IDL.Func([ProductId], [IDL.Opt(Product)], ['query']),
    'getProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
    'getProductsByCategory' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(Product)],
        ['query'],
      ),
    'getReviews' : IDL.Func([ProductId], [IDL.Vec(Review)], ['query']),
    'getSellerEarnings' : IDL.Func([SellerId], [IDL.Nat], ['query']),
    'getSellerOrders' : IDL.Func([SellerId], [IDL.Vec(Order)], ['query']),
    'getSellerProducts' : IDL.Func([SellerId], [IDL.Vec(Product)], ['query']),
    'getSellers' : IDL.Func([], [IDL.Vec(Seller)], ['query']),
    'getStripeSessionStatus' : IDL.Func([IDL.Text], [StripeSessionStatus], []),
    'getVerifiedSellers' : IDL.Func([], [IDL.Vec(Seller)], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'isStripeConfigured' : IDL.Func([], [IDL.Bool], ['query']),
    'setStripeConfiguration' : IDL.Func([StripeConfiguration], [], []),
    'transform' : IDL.Func(
        [TransformationInput],
        [TransformationOutput],
        ['query'],
      ),
    'updateOrderStatus' : IDL.Func([OrderId, IDL.Text], [IDL.Bool], []),
    'upsertProduct' : IDL.Func([Product], [], []),
    'verifySeller' : IDL.Func([SellerId], [IDL.Bool], []),
  });
};

export const init = ({ IDL }) => { return []; };